### ISSUE TITLE
Error cut_off_floor

### ISSUE THREAD

**Issue by blueja5** [EdwinTh/ggoutlier#1]
hello! thank you for providing this function which does exactly what I need to do right now. I have installed from git hub and put in my floor and ceiling values as shown (what do you advise when outliers only at one end?) but I get the following error? 

ggoutlier_hist(data, "CS17_diff_nIE", -309, 366)

Error in if (cut_off_floor < min(x[[var_name]])) { : 
  missing value where TRUE/FALSE needed

Any assistance gratefully received

**Comment by EdwinTh** [comment]
I am afraid I cannot reproduce your error with the information you provided. Would you be so kind to create a reprex? I will be happy to look into it.

https://www.tidyverse.org/help/

**Comment by blueja5** [comment]
Thanks, will do (managed to get error running reprex :-) ) - do you need a simplified copy of my data?

**Comment by EdwinTh** [comment]
Good, please do so. Or use mock data if possible.

**Comment by blueja5** [comment]
I think I have figured it out - I have NAs in my data, I just tested it on sample data with and without NA it worked on the latter. Is that right to you - I need to run this only on complete cases? Also, if I put 'NA' as the ceiling value it doesn't accept it as non-numerical. In your earlier ggoutlier_bin version I think this was an option. Is it possible with this if I only have outliers at one end? I have read your articles a couple of times but can't work out, apologies if being dim

**Comment by EdwinTh** [comment]
That makes sense, it is calculating the min of x, and it will return NA if there are NA's in x. I will update the function to allow for NA.

Indeed, in this version the ceiling and floor arguments are more strict. However, by default their values are `NA_real_`. If you want the bin to be omitted at one end, simply don't specify the argument at all.

**Comment by EdwinTh** [comment]
I have updated the package, you can now use the function when your variable contains NA values without having an error.

**Comment by blueja5** [comment]
Thank you so much, this now works perfectly for me. I think you responded on the old version that it may not be easy to use in a loop. Do you have a way of using this version in a loop by any chance?
