### ISSUE TITLE
Possible to pass arguments to geom_histogram ?

### ISSUE THREAD

**Issue by swiderskiji** [EdwinTh/ggoutlier#2]
I'm not certain how much it would take to do this, but I wonder if it might be possible to have ggoutlier pass arguments through to geom_histogram ?

For example, on my original histogram, I'm specifying 
`…   geom_histogram(binwidth = 5, boundary = 0, color = "#af8dc3", [etc]…`
to get it to set the boundaries between bins.  (So, my 0-5 bin sits between 0 and 5, not on the 0.)

But when I try to do the same thing in ggoutlier, I get an error message:  
```unused arguments (boundary = 0, color = "#af8dc3")```

I eventually figured out you called 'color' "col", so I was able to fix that, but I don't see a way to specify other arguments for geom_histogram that aren't named as arguments in ggoutlier_hist...

**Comment by EdwinTh** [comment]
The function has two arguments for the filling of the bars, see here for all the arguments to the function https://github.com/EdwinTh/ggoutlier/blob/master/R/ggoutlier_hist.R#L43

This function is a bit of a hack into `geom_histogram`, the regular ggplot arguments do not apply to it.
